# Generated by Django 4.2.6 on 2023-11-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя именованного URL-адреса'),
        ),
    ]
